apiVersion: v1
kind: Pod
metadata:
  name: sentinel
spec:
  containers:
  - name: sentinel
    image: sharework.cn/sentinel:1.8.4
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: service
      protocol: "TCP"
    
